#!/bin/sh

EN_SPACE=" "

case $BLOCK_BUTTON in
	1) kitty --class floatkitty nmtui ;;
	2) [ -n "$(cat /sys/class/net/wg0/operstate 2>/dev/null)" ] && sudo wg-quick down wg0 || sudo wg-quick up wg0 ;;
	3) notify-send "M1 to open nmtui

M3 to restart wg" ;;
   	6) kitty --class floatkitty micro ~/suckless/dwmblocks/sb-scripts/sb-internet ;;
esac

# Wifi signal strength
# if [ "$(cat /sys/class/net/wlan0/operstate 2>/dev/null)" = 'up' ] ; then
# 	wifiicon="$(awk '/^\s*w/ { print "󰒢", int($3 * 100 / 70) "% " }' /proc/net/wireless)"

# Wi-Fi
if [ "$(cat /sys/class/net/wlan0/operstate 2>/dev/null)" = 'up' ] ; 
then
    [ -n "$(cat /sys/class/net/wg0/operstate 2>/dev/null)" ] && wifiicon="󱚿" || wifiicon="󰖩"
else
    wifiicon=""
fi

# Ethernet
if [ "$(cat /sys/class/net/enp5s0/operstate 2>/dev/null)" = 'up' ] || [ "$(cat /sys/class/net/enp7s0/operstate 2>/dev/null)" = 'up' ]
then
    [ -n "$(cat /sys/class/net/wg0/operstate 2>/dev/null)" ] && ethericon="󰈁$EN_SPACE" || ethericon="󰈁$EN_SPACE"
else
    ethericon="󰈂$EN_SPACE"
fi

echo "| $ethericon$wifiicon$EN_SPACE$EN_SPACE"
