#! /bin/sh

echo ' '

case $BLOCK_BUTTON in
		1) rofi -show drun -theme ~/.config/rofi/config.rasi ;;
		# 2) playerctl previous; pkill -RTMIN+2 "${STATUSBAR:-dwmblocks}" ;;
		# 3) playerctl next; pkill -RTMIN+2 "${STATUSBAR:-dwmblocks}" ;;
		# 4) spotify-volume up ;;
		# 5) spotify-volume down ;;
		# 6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac
